package models

import "github.com/shopspring/decimal"

// Event wraps any state change or trade generated by the matching goroutine.
// Every event carries a per-symbol monotonic sequence number (Section 5).
type EventType string

const (
	EventOrderAccepted  EventType = "ORDER_ACCEPTED"
	EventOrderOpen      EventType = "ORDER_OPEN"
	EventOrderFilled    EventType = "ORDER_FILLED"
	EventOrderPartial   EventType = "ORDER_PARTIALLY_FILLED"
	EventOrderCancelled EventType = "ORDER_CANCELLED"
	EventOrderRejected  EventType = "ORDER_REJECTED"
	EventOrderExpired   EventType = "ORDER_EXPIRED"
	EventTrade          EventType = "TRADE"
	// EventTradeSettlementFailed is published instead of EventTrade when the
	// settlement handler returns an error. Downstream consumers must NOT treat
	// the trade as successful; the engine also halts the symbol for manual
	// reconciliation.
	EventTradeSettlementFailed EventType = "TRADE_SETTLEMENT_FAILED"
	EventBookDelta             EventType = "BOOK_DELTA"
	EventLiquidation           EventType = "LIQUIDATION"
	EventFunding               EventType = "FUNDING"
	// EventRealizedPnl is published whenever a futures position is (fully or
	// partially) closed, carrying the authoritative realized PnL/fee/margin
	// figures for that close so they can be persisted and queried later —
	// the settlement math already existed in FuturesSettlement.closePortion,
	// but was previously applied to the ledger only, never recorded.
	EventRealizedPnl EventType = "REALIZED_PNL"
)

// Event is published outbound from the matching goroutine.
type Event struct {
	Type           EventType `json:"type"`
	Symbol         string    `json:"symbol"`
	Market         string    `json:"market"`
	SequenceNumber uint64    `json:"sequenceNumber"`

	// Exactly one of the following will be non-nil per event type.
	Order       *Order       `json:"order,omitempty"`
	Trade       *Trade       `json:"trade,omitempty"`
	Liquidation *Liquidation `json:"liquidation,omitempty"`
	Funding     *Funding     `json:"funding,omitempty"`
	RealizedPnl *RealizedPnl `json:"realizedPnl,omitempty"`
}

// Liquidation describes a forced position close.
type Liquidation struct {
	AccountID string          `json:"accountId"`
	Symbol    string          `json:"symbol"`
	Side      OrderSide       `json:"side"`
	Size      decimal.Decimal `json:"size"`
	MarkPrice decimal.Decimal `json:"markPrice"`
}

// Funding describes a funding payment applied to a position.
type Funding struct {
	AccountID string          `json:"accountId"`
	Symbol    string          `json:"symbol"`
	Rate      decimal.Decimal `json:"rate"`
	Payment   decimal.Decimal `json:"payment"`
}

// RealizedPnl describes one position-closing settlement (full or partial).
// IsLiquidation distinguishes a forced close from a voluntary one; this
// engine has no separate "liquidation fee" concept — a liquidation is a
// normal reduce-only close that pays the same taker fee as any other trade,
// so no separate fee field exists here beyond what trades already record.
type RealizedPnl struct {
	AccountID      string          `json:"accountId"`
	Symbol         string          `json:"symbol"`
	ClosedQty      decimal.Decimal `json:"closedQty"`
	Pnl            decimal.Decimal `json:"pnl"`
	MarginReturned decimal.Decimal `json:"marginReturned"`
	IsLiquidation  bool            `json:"isLiquidation"`
}
