package models

import (
	"time"

	"github.com/shopspring/decimal"
)

// Trade represents a completed match between a resting and an aggressing order.
// It is generated by the matching loop and carries no asset-class-specific fields.
type Trade struct {
	ID           string          `json:"id"`
	Symbol       string          `json:"symbol"`
	Market       MarketType      `json:"market"`
	MakerOrderID string          `json:"makerOrderId"`
	TakerOrderID string          `json:"takerOrderId"`
	MakerSide    OrderSide       `json:"makerSide"`
	Price        decimal.Decimal `json:"price"`
	Quantity     decimal.Decimal `json:"quantity"`
	ExecutedAt   time.Time       `json:"executedAt"`

	// SequenceNumber is assigned by the matching goroutine before publishing.
	// It is monotonically increasing per symbol and used by downstream
	// consumers to detect gaps and reorder events.
	SequenceNumber uint64 `json:"sequenceNumber"`

	// Transient: populated by the matching engine for settlement; not serialized.
	BuyOrder  *Order `json:"-"`
	SellOrder *Order `json:"-"`
}
