package models

import (
	"time"

	"github.com/shopspring/decimal"
)

// Trade represents a completed match between a resting and an aggressing order.
// It is generated by the matching loop and carries no asset-class-specific fields.
type Trade struct {
	ID           string          `json:"id"`
	Symbol       string          `json:"symbol"`
	Market       MarketType      `json:"market"`
	MakerOrderID string          `json:"makerOrderId"`
	TakerOrderID string          `json:"takerOrderId"`
	MakerSide    OrderSide       `json:"makerSide"`
	Price        decimal.Decimal `json:"price"`
	Quantity     decimal.Decimal `json:"quantity"`
	ExecutedAt   time.Time       `json:"executedAt"`

	// Fees charged at settlement, denominated in the quote currency.
	// Zero when the symbol has no fee configuration.
	MakerFeePaid decimal.Decimal `json:"makerFeePaid"`
	TakerFeePaid decimal.Decimal `json:"takerFeePaid"`

	// SequenceNumber is assigned by the matching goroutine before publishing.
	// It is monotonically increasing per symbol and used by downstream
	// consumers to detect gaps and reorder events.
	SequenceNumber uint64 `json:"sequenceNumber"`

	// Transient: populated by the matching engine for settlement; not serialized.
	BuyOrder  *Order `json:"-"`
	SellOrder *Order `json:"-"`
}

// Copy returns a deep copy, including nil-safe copies of BuyOrder/SellOrder,
// safe for handing to callers outside the engine goroutine.
func (t *Trade) Copy() *Trade {
	if t == nil {
		return nil
	}
	c := *t
	c.BuyOrder = t.BuyOrder.Copy()
	c.SellOrder = t.SellOrder.Copy()
	return &c
}
